# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Copy Python script
COPY server.py /app/server.py

# Install dependencies
RUN pip install --no-cache-dir "mcp[cli]>=1.6.0" "security-cli>=0.1.0"

# Expose standard port environment will be provided
ENV PORT 8000

# Default command to run the MCP server
CMD ["python", "server.py"]
