[project]
name = "enrichment-mcp"
version = "0.1.0"
description = "A simple enrichment MCP server for security data enrichment."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.6.0",
    "security-cli>=0.1.0",
]
